<?php

/**
 * @file
 * Drupal tweaks settings to improve your functionality on your website
 *
 * @version
 *   $Id$
 *
 * @developers
 *   Rafal Wieczorek <kenorb@gmail.com>
 */

/**
 * Minimum recommended value of PHP memory_limit.
 */
define('DRUPAL_MINIMUM_PHP_MEMORY_LIMIT', '16M'); 
/**
 * Minimum recommended value of PHP max_execution_time limit.
 */
define('DRUPAL_MINIMUM_MAX_EXECUTION_TIME', '30'); 

/**
 * Implementation of hook_menu().
 */
function drupal_tweaks_menu() { 
  $items['admin/drupal_tweaks'] = array(
    'title' => 'Content management',
    'description' => "Manage your Drupal tweaks.",
    'position' => 'left',
    'weight' => -10,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer drupal_tweaks'),
    'file' => 'system.admin.inc',
  ); 

  /* GENERAL PAGE */
  $items['admin/drupal_tweaks/general'] = array(
    'title' => 'General',
    'description' => t('General module and node operations.'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -2,
  ); 
  $items['admin/drupal_tweaks'] = array(
    'title' => 'Drupal tweaks',
    'description' => t('General tweak operations.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('drupal_tweaks_general_op_form'),
    'access arguments' => array('administer drupal_tweaks'),
    'file' => 'includes/drupal_tweaks.admin.inc',
  );
  $items['admin/drupal_tweaks/autocomplete/enabled_modules'] = array(
    'title' => 'Enable the module.',
    'page callback' => 'drupal_tweaks_autocomplete_modules',
    'access callback' => 'user_access',
    'access arguments' => array('administer drupal_tweaks'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/drupal_tweaks.ajax.inc',
  );
  $items['admin/drupal_tweaks/autocomplete/disabled_modules'] = array(
    'title' => 'Disable the module.',
    'page callback' => 'drupal_tweaks_autocomplete_modules',
    'access callback' => 'user_access',
    'access arguments' => array('administer drupal_tweaks'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/drupal_tweaks.ajax.inc',
  );
  $items['admin/drupal_tweaks/autocomplete/nodes'] = array(
    'title' => 'Find the node.',
    'page callback' => 'drupal_tweaks_autocomplete_nodes',
    'page arguments' => array(0),
    'access callback' => 'user_access',
    'access arguments' => array('administer drupal_tweaks'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/drupal_tweaks.ajax.inc',
  );

  /* OPERATION PAGE */
  $items['admin/drupal_tweaks/op'] = array(
    'title' => 'Operations',
    'description' => t('Flush operations (clear cache, rebuild permissions, etc.)'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('drupal_tweaks_op_form'),
    'access arguments' => array('administer drupal_tweaks'),
    'file' => 'includes/drupal_tweaks.admin.op.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 2,
  );
  $items['admin/drupal_tweaks/op/rebuild_perm'] = array(
    'title' => 'Rebuild permissions',
    'page arguments' => array('drupal_tweaks_rebuild_perm_confirm'),
    'file' => 'includes/drupal_tweaks.admin.op.inc',
    'access arguments' => array('administer drupal_tweaks'),
    'type' => MENU_CALLBACK,
  ); 
  $items['admin/drupal_tweaks/op/clear_cache'] = array(
    'title' => 'Rebuild cache',
    'page arguments' => array('drupal_tweaks_clear_cache_submit'),
    'file' => 'includes/drupal_tweaks.admin.op.inc',
    'access arguments' => array('administer drupal_tweaks'),
    'type' => MENU_CALLBACK,
  ); 
  /* BLOCK PAGE */
/* TODO
  $items['admin/drupal_tweaks/block'] = array(
    'title' => 'Blocks',
    'description' => t('Block conversion operations.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('drupal_tweaks_block_form'),
    'access arguments' => array('administer drupal_tweaks'),
    'file' => 'includes/drupal_tweaks.admin.block.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 3,
  );
*/

  /* TWEAKS MODULE PAGE */
  $items['admin/drupal_tweaks/module_tweaks'] = array(
    'title' => 'Tweaks',
    'description' => t('Tweaks settings for Drupal modules.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('drupal_tweaks_general_tweaks_form'),
    'access arguments' => array('administer drupal_tweaks'),
    'file' => 'includes/drupal_tweaks.admin.tweaks.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 4,
  );

  /* PHP SETTINGS PAGE */
  $items['admin/drupal_tweaks/php'] = array(
    'title' => 'PHP',
    'description' => t('PHP Settings.'),
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('drupal_tweaks_php_settings_form'), 
    'access arguments' => array('administer drupal_tweaks'),
    'file' => 'includes/drupal_tweaks.admin.php.inc', 
    'type' => MENU_LOCAL_TASK,
    'weight' => 5,
  );

  /* SETTINGS PAGE */
  $items['admin/drupal_tweaks/settings'] = array(
    'title' => 'Settings',
    'description' => t('Drupal Tweaks module settings.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('drupal_tweaks_general_settings_form'),
    'access arguments' => array('administer drupal_tweaks'),
    'file' => 'includes/drupal_tweaks.admin.settings.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 7,
  );

  /* REPORT PAGE */
  $items['admin/drupal_tweaks/suggestions'] = array(
    'title' => 'Suggestions',
    'description' => t('Check for problems or suggestions with your website.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('drupal_tweaks_report_form'),
    'access arguments' => array('administer drupal_tweaks'),
    'file' => 'includes/drupal_tweaks.admin.suggestions.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 8,
  );

  return $items;
}


/**
 * Implementation of hook_init().
 */
function drupal_tweaks_boot() {
  /* PHP TWEAKS */
  if (variable_get('drupal_tweaks_php_activated', FALSE)) {
    /* LOAD INCLUDES */
    include_once './includes/common.inc'; // for t() called from menu_get_item() AND drupal_get_path() called from module_load_include()
    include_once './includes/path.inc';   // for arg() called from menu_get_item()
    include_once './includes/unicode.inc';   // for drupal_strtolower() called from parse_size()
    module_load_include('inc', 'drupal_tweaks'); // load additional function from included file

    /* LOAD DB SETTINGS */
    $php_conf = drupal_tweaks_get_php_configuration(TRUE);

    /* validate PHP */
    foreach ($php_conf as $var_name => $var_values) {
        // update mysql settings if necessary
        if ($var_values['conf'] <> $var_values['php']) {
            if (!ini_set($var_name, $var_values['conf'])) {
              drupal_set_message(t('Cannot set variable `%variable` to `%value` in your PHP configuration!', array('%variable' => $var_name, '%value' => $var_values['conf'])). t('<br>') . t('Probably you do not have proper privileges.'), 'error');
              variable_set($var_name, $var_values['php']); // reverting changes in settings (to prevent showing error message)
            }
        }
    }
  }
}

/**
 * Implementation of hook_form_alter().
 */
function drupal_tweaks_form_alter(&$form, $form_state, $form_id) {
  //drupal_set_message($form_id);
  /* MODULE TWEAKS */
  switch ($form_id) {
    case 'node_admin_content':
      // TODO: something here?
      break;
    case 'filter_admin_format_form':
      if (variable_get('drupal_tweaks_filter_tweak', TRUE)) {
        /* add module name on each filter name (See: admin/settings/filters/1) */
        foreach (filter_list_all() as $filter_key => $filter_data) {
          if (array_key_exists($filter_key, $form['filters'])) {
            $form['filters'][$filter_key]['#title'] .= " ($filter_data->module)";
          }
        }
      }
      break;
    case 'views_ui_list_views_form':
      if (variable_get('drupal_tweaks_views_tweak', TRUE)) {
        views_include_default_views(); 
        // Invoke hook_views_default_views for all modules.
        foreach (module_implements('views_default_views') as $module) {
          $default_views = module_invoke($module, 'views_default_views');
          $view_names = array_keys($default_views);
          foreach ($view_names as $view_name) {
            if (array_key_exists($view_name, $form['#parameters'][1]['views'])) {
              $desc = &$form['#parameters'][1]['views'][$view_name]->description;
              $desc = t('Module: ') . $module . '; ' . $desc;
            }
          }
        } 
      }
      break;
  }
}

/**
 * Implementation of hook_perm().
 */
function drupal_tweaks_perm() {
   return array('administer drupal_tweaks');
}

/**
 * Implementation of hook_exit().
 */
function drupal_tweaks_exit() {
}

